version: "3.9"

services:
  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - fastapi

  fastapi_service:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    hostname: fastapi_service
    container_name: fastapi_service
    restart: always
    command: ["/fastapi_service/build.sh"]
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ./:/home/app
    depends_on:
      - redis-cache
    networks:
      - fastapi

volumes:

  cache:
    driver: local

networks:
  fastapi:
    name: "fastapi-network"